module.exports = [
    { newsarticle_id: 1, preference_id: 1 },
    { newsarticle_id: 2, preference_id: 1 },
    { newsarticle_id: 3, preference_id: 1 },
    { newsarticle_id: 4, preference_id: 1 },
    { newsarticle_id: 5, preference_id: 1 },
    { newsarticle_id: 6, preference_id: 1 },
    { newsarticle_id: 7, preference_id: 1 },
    { newsarticle_id: 8, preference_id: 1 },
    { newsarticle_id: 9, preference_id: 1 },
    { newsarticle_id: 10, preference_id: 1 },
    { newsarticle_id: 11, preference_id: 1 },
    { newsarticle_id: 12, preference_id: 1 },
    { newsarticle_id: 13, preference_id: 1 },
    { newsarticle_id: 14, preference_id: 1 },
    { newsarticle_id: 15, preference_id: 1 },
    { newsarticle_id: 16, preference_id: 1 },
    { newsarticle_id: 17, preference_id: 1 },
    { newsarticle_id: 18, preference_id: 1 }
]